### ISSUE TITLE
使用fabric改写并为星星绑定事件

### ISSUE THREAD

**Issue by yanfuyou** [DoWake/PersonalPage#1]
#你好,我想用fabric改写这个效果，但是发现会卡顿并且clear会直接清除背景，使用getContext.clearRect()也是,我是写后端的，不是很了解canvas，可以帮忙看下吗？谢谢
const StarrySky = (function () {
  let canvasElement;
  let canvas;
  let starList;
  let starColorList;
  let starRadius;
  let focalDistanceLevel;
  let starCountLevel;
  let starSpeedLevel;
  let focalDistance;
  let starCount;
  let rAF;
  let lastCircle = [];
  return {
    init: function (canvas_element) {
      if (canvas_element && canvas_element.nodeName === "CANVAS") {
        canvasElement = canvas_element;
        const sizeMap = getContainerSize();
        canvas = new fabric.Canvas(canvasElement);
        canvas.setWidth(sizeMap.get("width"));
        canvas.setHeight(sizeMap.get("height"));
        canvas.setBackgroundColor("black");
        starColorList = ["rgb(255, 255, 255)"];
        starRadius = 1;
        focalDistanceLevel = 0.4;
        starCountLevel = 0.2;
        starSpeedLevel = 0.0005;
        focalDistance = canvas.getWidth() * focalDistanceLevel;
        starCount =
          Math.ceil(canvas.getWidth() * starCountLevel) > 100
            ? 100
            : Math.ceil(canvas.getWidth() * starCountLevel);
        starList = [];

        for (let i = 0; i < starCount; i++) {
          const starTemp = {
            left: canvas.getWidth() * (0.1 + 0.8 * Math.random()),
            top: canvas.getHeight() * (0.1 + 0.8 * Math.random()),
            z: focalDistance * Math.random(),
            fill: starColorList[Math.floor(Math.random() * starColorList.length)],
            id: i,
          };
          starList[i] = starTemp;
        }

        window.addEventListener("resize",function () {
          const parentNode = document.getElementById("outer");
          const sizeMap = getContainerSize();
          canvas.setWidth(sizeMap.get("width"));
          canvas.setHeight(sizeMap.get("height"));
          focalDistance = canvas.getWidth() * focalDistanceLevel;

          const starCount2 = Math.ceil(canvas.getWidth() * starCountLevel);
          if (starCount > starCount2) {
            starList.splice(starCount2);
          } else {
            let num = starCount2 - starCount;
            while (num--) {
              starList.push({
                left: canvas.getWidth() * (0.1 + 0.8 * Math.random()),
                top: canvas.getHeight() * (0.1 + 0.8 * Math.random()),
                z: focalDistance * Math.random(),
                fill: starColorList[Math.floor(Math.random() * starColorList.length)],
              });
            }
          }
          starCount = Math.ceil(canvas.getWidth() * starCountLevel);
        });
      } else {
        console.error("初始化失败,必须传入Canvas元素");
      }
    },

    setSkyColor: function (sky_color = "black") {
      canvas.setBackgroundColor(sky_color).renderAll();
    },

    setStarRadius: function (star_radius = 1) {
      starRadius = star_radius;
    },

    setFocalDistanceLevel: function (focal_distance_level = 0.4) {
      focalDistanceLevel = focal_distance_level;
      focalDistance = canvas.getWidth() * focalDistanceLevel;
    },

    setStarCountLevel: function (star_count_level = 0.2) {
      starCountLevel = star_count_level;
      const starCount2 = Math.ceil(canvas.getWidth() * starCountLevel);
      if (starCount > starCount2) {
        starList.splice(starCount2);
      } else {
        let num = starCount2 - starCount;
        while (num--) {
          starList.push({
            left: canvas.getWidth() * (0.1 + 0.8 * Math.random()),
            top: canvas.getHeight() * (0.1 + 0.8 * Math.random()),
            z: focalDistance * Math.random(),
            fill: starColorList[Math.floor(Math.random() * starColorList.length)],
          });
        }
      }
      starCount = Math.ceil(canvas.getWidth() * starCountLevel);
    },
    setStarSpeedLevel: function (star_speed_level = 0.005) {
      starSpeedLevel = star_speed_level;
    },
    setStarColorList: function (color, mode = false) {
      if (typeof color === "object") {
        starColorList = color;
      } else if (typeof color === "string") {
        starColorList.push(color);
      }
      if (mode) {
        for (let i = 0; i < starList.length; i++) {
          starList[i]["fill"] =
            starColorList[Math.floor(Math.random() * starColorList.length)];
        }
        canvas.renderAll();
      }
    },
    render: function () {
      if (!stop.value) {
        const starSpeed = canvas.getWidth() * focalDistanceLevel * starSpeedLevel;
        // 清空画布
        //有卡顿
        // lastCircle.forEach((star) => {
        //   canvas.remove(star);
        // });
        // console.log(canvas)
        // if(!canvas.isEmpty()){
        //   console.log(canvas)
          // canvas = canvas.clearContext(canvas.getContext()).contextContainer;
        //   console.log(canvas)
        //   // return;
        // }
        // 计算位置
        lastCircle.length = 0;
        starList.forEach(function (star) {
          const star_x =
            (star.left - canvas.getWidth() / 2) * (focalDistance / star.z) +
            canvas.getWidth() / 2;
          const star_y =
            (star.top - canvas.getHeight() / 2) * (focalDistance / star.z) +
            canvas.getHeight() / 2;
          star.z -= starSpeed;

          if (
            star.z > 0 &&
            star.z <= focalDistance &&
            star_x >= -20 &&
            star_x <= canvas.getWidth() + 20 &&
            star_y >= -20 &&
            star_y <= canvas.getHeight() + 20
          ) {
            const star_radius = starRadius * ((focalDistance / star.z) * 0.8);
            // 把半径也保存起来
            star.radius = star_radius;
            const star_opacity = 1 - 0.8 * (star.z / focalDistance);
            const star_fill = star.fill
              .replace("rgb", "rgba")
              .replace(")", `, ${star_opacity})`);

            // 创建星星对象及设置属性
            const starCircle = new fabric.Circle({
              left: star_x,
              top: star_y,
              radius: star_radius,
              fill: star_fill,
              shadow: `0 0 10px ${star.fill}`,
              hasBorders: false, // 显示边框
              hasControls: false //显示控制点
            });
            // 添加星星对象到canvas
            lastCircle.push(starCircle);
            starCircle.id = star.id;
            starCircle.on('mousedown',(options)=>{
              console.log(options.target.id)
            })
            // console.log(starCircle);
            canvas.add(starCircle);
          } else {
            const z = focalDistance * Math.random();
            star.left = canvas.getWidth() * (0.1 + 0.8 * Math.random());
            star.top = canvas.getHeight() * (0.1 + 0.8 * Math.random());
            star.z = z;
            star.fill = starColorList[Math.floor(Math.random() * starColorList.length)];
          }
        });

        // 动画循环
        const self = this;
        rAF = fabric.util.requestAnimFrame(function () {
          self.render();
        });
      }
    },
    destroy: function () {
      fabric.util.cancelAnimFrame(rAF);
      starList = [];
      canvas.clear();
      canvas.setWidth(0);
      canvas.setHeight(0);
      canvas.dispose();
    },

    debounce: function (func, time = 200) {
      let timeId;
      return function () {
        if (timeId) {
          clearTimeout(timeId);
        }
        timeId = setTimeout(function () {
          func();
        }, time);
      };
    },

    throttle: function (func, time = 200) {
      let timeId = null;
      let pre = 0;
      return function () {
        if (Date.now() - pre > time) {
          clearTimeout(timeId);
          pre = Date.now();
          func();
        } else {
          timeId = setTimeout(func, time);
        }
      };
    },
  };
})();

**Comment by DoWake** [comment]
你好，方便提供一下你改写的项目地址吗？另外，你使用哪个浏览器出现了卡顿。你可以尝试把你改写的
```
rAF = fabric.util.requestAnimFrame(function () {
      self.render();
});
```
改成原来的，测试是否仍存在卡顿。

**Comment by yanfuyou** [comment]
地址 https://github.com/yanfuyou/satori-web-page
提交记录：cf3075ac5fee8dc261c03d8e2aa8987f298ecba9
改写后的使用谷歌浏览器会卡顿，最新的提交是用的您写的是不卡的。但是我想给星星添加绑定事件所以使用了fabric

**Comment by DoWake** [comment]
Hello！我拉取了你的代码，我发现造成卡顿的原因应该是性能问题导致的。每次渲染的时候你都创建了新的fabric.Circle对象，但实际上并不需要。你可以通过修改原来的fabric.Circle对象的配置来实现动态移动星星，并绑定事件。我在网上查了一下fabric的资料，官方提供了动态修改配置的接口。下面是我写的一个的示例，你可以参考一下，使用fabric对StarrySky.js进行改造。

    ```
<script>
      const canvas = new fabric.Canvas("canvas");
      //初始化
      const info = {
        left: 20,
        top: 20,
        radius: 8,
        fill: "rgba(20, 40, 130, 0.6)",
        shadow: "0 0 10px rgba(20, 40, 130, 0.3)",
        hasBorders: false,
        hasControls: false,
      };
      const starCircle = new fabric.Circle(info);
      canvas.add(starCircle);
      render();
      //动态修改
      function render() {
        info.left += 2;
        info.top += 4;
        canvas.remove(starCircle);
        starCircle.setOptions(info);
        canvas.add(starCircle);
        fabric.util.requestAnimFrame(function () {
          render();
        });
      }
    </script>
```
你可以在starList初始化的时候，创建并保存fabric.Circle的实例。每次渲染时，计算星星的x、y的值，先使用canvas.remove(starCircle)移除，通过setOptions动态改变fabric.Circle实例配置，再重新添加到canvas中。

**Comment by DoWake** [comment]
> 地址 https://github.com/yanfuyou/satori-web-page 提交记录：cf3075ac5fee8dc261c03d8e2aa8987f298ecba9 改写后的使用谷歌浏览器会卡顿，最新的提交是用的您写的是不卡的。但是我想给星星添加绑定事件所以使用了fabric

Hello！我拉取了你的代码，我发现造成卡顿的原因应该是性能问题导致的。每次渲染的时候你都创建了新的fabric.Circle对象，但实际上并不需要。你可以通过修改原来的fabric.Circle对象的配置来实现动态移动星星，并绑定事件。我在网上查了一下fabric的资料，官方提供了动态修改配置的接口。下面是我写的一个的示例，你可以参考一下，使用fabric对StarrySky.js进行改造。

```
    <script>
      const canvas = new fabric.Canvas("canvas");

      //初始化
      const info = {
        left: 20,
        top: 20,
        radius: 8,
        fill: "rgba(20, 40, 130, 0.6)",
        shadow: "0 0 10px rgba(20, 40, 130, 0.3)",
        hasBorders: false,
        hasControls: false,
      };
      const starCircle = new fabric.Circle(info);
      canvas.add(starCircle);
      render();
      //动态修改
      function render() {
        info.left += 2;
        info.top += 4;
        canvas.remove(starCircle);
        starCircle.setOptions(info);
        canvas.add(starCircle);
        fabric.util.requestAnimFrame(function () {
          render();
        });
      }
    </script>
```
你可以在starList初始化的时候，创建并保存fabric.Circle的实例。每次渲染时，计算星星的x、y的值，先使用canvas.remove(starCircle)移除，通过setOptions动态改变fabric.Circle实例配置，再重新添加到canvas中。

**Comment by yanfuyou** [comment]
好的，谢谢
